# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
